#pragma once


#if defined(STATIC_BUILD)
#	define MADGINE_ANDROIDINPUT_EXPORT
#	define MADGINE_ANDROIDINPUT_TEMPLATE_INSTANTIATION TEMPLATE_INSTANTIATION
#else
#	if defined(AndroidInput_EXPORTS)
#		define MADGINE_ANDROIDINPUT_EXPORT DLL_EXPORT
#		define MADGINE_ANDROIDINPUT_TEMPLATE_INSTANTIATION TEMPLATE_INSTANTIATION_EXPORT
#	else
#		define MADGINE_ANDROIDINPUT_EXPORT DLL_IMPORT
#		define MADGINE_ANDROIDINPUT_TEMPLATE_INSTANTIATION TEMPLATE_INSTANTIATION_IMPORT
#	endif
#endif


#include "client/clientlib.h"