set (GRAPHVIZ_EXTERNAL_LIBS FALSE)
set (GRAPHVIZ_STATIC_LIBS FALSE)
set (GRAPHVIZ_MODULE_LIBS FALSE)
set (GRAPHVIZ_EXECUTABLES FALSE)
set (GRAPHVIZ_IGNORE_TARGETS assimp freetype lib_msdfgen stb zlib ImGui Im3D imgui_node_editor .*Tools .*Serialize .*Nodes Modules Interfaces Generic Meta)