#pragma once

namespace Maditor {
	namespace Shared {
		enum ErrorCode {
			NO_ERROR_SHARED = 0,
			FAILED_START_SERVER = 100,
			MADITOR_CONNECTION_TIMEOUT,
			DEBUGGER_CONNECTION_TIMEOUT,
			MODULE_LOAD_FAILED,
			APP_INIT_FAILED,
			MADITOR_DISCONNECTED,
			FAILED_CREATE_SERVER_CLASS,
			ILLEGAL_ARGUMENTS,
			KILL_PING_TIMEOUT,
			KILL_NO_APPLICATION_NOTIFICATION,
			KILL_FAILED_CONNECTION,
			KILL_CLEANUP,
			KILL_USER_REQUEST,
			APPLICATION_INFO_TIMEOUT,
			UNSUPPORTED_LAUNCHER_TYPE
		};

		std::string MADITOR_SHARED_EXPORT to_string(ErrorCode cause);
	}
}