#pragma once

#define SHARED_LIB_PREFIX \
    "${CMAKE_SHARED_LIBRARY_PREFIX}"
#define SHARED_LIB_SUFFIX \
    "${CMAKE_SHARED_LIBRARY_SUFFIX}"

#cmakedefine01 MODULES_ENABLE_PLUGINS
#cmakedefine01 MODULES_ENABLE_TASK_TRACKING

//plugins
#define ENABLE_PLUGINS MODULES_ENABLE_PLUGINS

#define ENABLE_TASK_TRACKING MODULES_ENABLE_TASK_TRACKING