#pragma once

#define SHARED_LIB_PREFIX \
    "${CMAKE_SHARED_LIBRARY_PREFIX}"
#define SHARED_LIB_SUFFIX \
    "${CMAKE_SHARED_LIBRARY_SUFFIX}"

#cmakedefine01 MODULES_ENABLE_PLUGINS
#cmakedefine01 MODULES_ENABLE_TASK_TRACKING

#cmakedefine01 MODULES_ENABLE_THREADING
#cmakedefine01 MODULES_USE_CUSTOM_THREADLOCAL
#cmakedefine01 MODULES_USE_PTHREAD_THREADLOCAL_STORE

//plugins
#define ENABLE_PLUGINS MODULES_ENABLE_PLUGINS

#define ENABLE_TASK_TRACKING MODULES_ENABLE_TASK_TRACKING

//threading
#define ENABLE_THREADING MODULES_ENABLE_THREADING
#define USE_CUSTOM_THREADLOCAL MODULES_USE_CUSTOM_THREADLOCAL
#define USE_PTHREAD_THREADLOCAL_STORE MODULES_USE_PTHREAD_THREADLOCAL_STORE
