#pragma once

#cmakedefine01 MODULES_ENABLE_PLUGINS
#cmakedefine01 MODULES_ENABLE_TASK_TRACKING

//plugins
#define ENABLE_PLUGINS MODULES_ENABLE_PLUGINS

#define ENABLE_TASK_TRACKING MODULES_ENABLE_TASK_TRACKING