#pragma once

#include "clientlib.h"

#if defined(STATIC_BUILD)
#	define MADGINE_EMSCRIPTENINPUT_EXPORT
#	define MADGINE_EMSCRIPTENINPUT_TEMPLATE_INSTANTIATION TEMPLATE_INSTANTIATION
#else
#	if defined(EmscriptenInput_EXPORTS)
#		define MADGINE_EMSCRIPTENINPUT_EXPORT DLL_EXPORT
#		define MADGINE_EMSCRIPTENINPUT_TEMPLATE_INSTANTIATION TEMPLATE_INSTANTIATION_EXPORT
#	else
#		define MADGINE_EMSCRIPTENINPUT_EXPORT DLL_IMPORT
#		define MADGINE_EMSCRIPTENINPUT_TEMPLATE_INSTANTIATION TEMPLATE_INSTANTIATION_IMPORT
#	endif
#endif


