#pragma once

#cmakedefine GENERIC_COMPATIBILITY_CONFIG_HEADER "${GENERIC_COMPATIBILITY_CONFIG_HEADER}"


#ifdef GENERIC_COMPATIBILITY_CONFIG_HEADER
#    define COMPATIBILITY_CONFIG_HEADER GENERIC_COMPATIBILITY_CONFIG_HEADER
#endif
