#pragma once

#include "Madgine/clientlib.h"

#include "apisforward.h"


#if defined(STATIC_BUILD)
#define MADGINE_APIS_EXPORT
#define MADGINE_APIS_TEMPLATE_INSTANTIATION TEMPLATE_INSTANTIATION
#else
#if defined(Apis_EXPORTS)
#define MADGINE_APIS_EXPORT DLL_EXPORT
#define MADGINE_APIS_TEMPLATE_INSTANTIATION TEMPLATE_INSTANTIATION_EXPORT
#else
#define MADGINE_APIS_EXPORT DLL_IMPORT
#define MADGINE_APIS_TEMPLATE_INSTANTIATION TEMPLATE_INSTANTIATION_IMPORT
#endif
#endif

#include <numeric>