#pragma once

/// @cond

#if defined(STATIC_BUILD)
#	define MADGINE_OIS_EXPORT
#	define MADGINE_OIS_TEMPLATE_INSTANTIATION TEMPLATE_INSTANTIATION
#else
#	if defined(OISHandler_EXPORTS)
#		define MADGINE_OIS_EXPORT DLL_EXPORT
#		define MADGINE_OIS_TEMPLATE_INSTANTIATION TEMPLATE_INSTANTIATION_EXPORT
#	else
#		define MADGINE_OIS_EXPORT DLL_IMPORT
#		define MADGINE_OIS_TEMPLATE_INSTANTIATION TEMPLATE_INSTANTIATION_IMPORT
#	endif
#endif

#include "Madgine/clientlib.h"


/// @endcond
