#pragma once

#include "Madgine/clientlib.h"
#include "apislib.h"

#include "toolsforward.h"


#if defined(STATIC_BUILD)
#define MADGINE_TOOLS_EXPORT
#define MADGINE_TOOLS_TEMPLATE_INSTANTIATION TEMPLATE_INSTANTIATION
#else
#if defined(Tools_EXPORTS)
#define MADGINE_TOOLS_EXPORT DLL_EXPORT
#define MADGINE_TOOLS_TEMPLATE_INSTANTIATION TEMPLATE_INSTANTIATION_EXPORT
#else
#define MADGINE_TOOLS_EXPORT DLL_IMPORT
#define MADGINE_TOOLS_TEMPLATE_INSTANTIATION TEMPLATE_INSTANTIATION_IMPORT
#endif
#endif

#include <algorithm>