#pragma once

#include "Modules/moduleslib.h"

#if defined(STATIC_BUILD)
#    define MADGINE_IMAGELOADER_EXPORT
#    define MADGINE_IMAGELOADER_TEMPLATE_INSTANTIATION TEMPLATE_INSTANTIATION
#else
#    if defined(ImageLoader_EXPORTS)
#        define MADGINE_IMAGELOADER_EXPORT DLL_EXPORT
#        define MADGINE_IMAGELOADER_TEMPLATE_INSTANTIATION TEMPLATE_INSTANTIATION_EXPORT
#    else
#        define MADGINE_IMAGELOADER_EXPORT DLL_IMPORT
#        define MADGINE_IMAGELOADER_TEMPLATE_INSTANTIATION TEMPLATE_INSTANTIATION_IMPORT
#    endif
#endif