#pragma once

#define SHARED_LIB_PREFIX \
    "${CMAKE_SHARED_LIBRARY_PREFIX}"
#define SHARED_LIB_SUFFIX \
	"${CMAKE_SHARED_LIBRARY_SUFFIX}"

#cmakedefine01 INTERFACES_ENABLE_THREADING
#cmakedefine01 INTERFACES_USE_CUSTOM_THREADLOCAL
#cmakedefine01 INTERFACES_USE_PTHREAD_THREADLOCAL_STORE

#cmakedefine01 INTERFACES_ENABLE_PROFILER
#cmakedefine01 INTERFACES_ENABLE_MEMTRACKING

//threading
#define ENABLE_THREADING INTERFACES_ENABLE_THREADING
#define USE_CUSTOM_THREADLOCAL INTERFACES_USE_CUSTOM_THREADLOCAL
#define USE_PTHREAD_THREADLOCAL_STORE INTERFACES_USE_PTHREAD_THREADLOCAL_STORE

//profiler
#define ENABLE_PROFILER INTERFACES_ENABLE_PROFILER
#define ENABLE_MEMTRACKING INTERFACES_ENABLE_MEMTRACKING