#pragma once

#define IMGUI_ICON_AXES "\xef\x84\x81"
#define IMGUI_ICON_BLANK "\xef\x84\x82"
#define IMGUI_ICON_ERROR "\xef\x84\x83"
#define IMGUI_ICON_FILE "\xef\x84\x84"
#define IMGUI_ICON_FOLDER "\xef\x84\x85"
#define IMGUI_ICON_GRID "\xef\x84\x86"
#define IMGUI_ICON_INFO "\xef\x84\x87"
#define IMGUI_ICON_PAUSE "\xef\x84\x88"
#define IMGUI_ICON_PLAY "\xef\x84\x89"
#define IMGUI_ICON_PLUS "\xef\x84\x8a"
#define IMGUI_ICON_POINTLIGHT "\xef\x84\x8b"
#define IMGUI_ICON_REQUEST_IN "\xef\x84\x8c"
#define IMGUI_ICON_SKELETON "\xef\x84\x8d"
#define IMGUI_ICON_STOP "\xef\x84\x8e"
#define IMGUI_ICON_WARNING "\xef\x84\x8f"
#define IMGUI_ICON_X "\xef\x84\x90"
